### ISSUE TITLE
Error bars appear elongated on plot with multiple lines, right click causes error

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mslice#797] opened 2022-06-17 14:15 UTC
**Describe the bug**
Error markers appear elongated, when right clicking these lines an error is thrown. This error bar bug has been present since 6.3, but the error is now only thrown upon right clicking since the update to `matplotlib 3.5.2`

**Note: right clicking on any error bar throws error, not just elongated ones.**

**To Reproduce**
Steps to reproduce the behaviour:
1. Load MAR21335_Ei60meV
2. Create a cut from 0 to 10, -5 to 5, with a width of 2.5
3. Observe elongated error bars which have been plotted
4. Right click said error bars, observe error.

**Expected behaviour**
Error bars should not be elongated. There should be no error upon right clicking.

![image](https://user-images.githubusercontent.com/95620982/174315842-c84370e7-7477-41cd-b425-32af70c6dd2d.png)

**Comment by robertapplin** [comment] 2023-03-30 08:27
Closing as @MialLewis and I cannot reproduce the crash

**Closed by robertapplin** 2023-03-30 08:27 UTC
Labels: bug
