### ISSUE TITLE
Axis not scaling properly

### ISSUE THREAD

**Issue by GuiMacielPereira** [mantidproject/mslice#1000] opened 2024-09-20 16:21 UTC
**Describe the bug**
Followed instructions at https://developer.mantidproject.org/Testing/Direct/MSliceTestGuide.html#changing-the-intensity-of-a-cut
After I selected Chi''(Q,E) and typed in 100, the y axis did not rescale as supposed.

**To Reproduce**
Reported on macOS, I tried reproducing it on Linux but the axes did scale correctly.

**Expected behavior**
The axis should scale on macOS.

**Screenshots**
If applicable/possible, add screenshots to help explain your problem.

**MSlice Version (please complete the following information):**
 - MSlice Version 2.9.0

**Additional context**
Found during manual testing.

**Comment by SilkeSchomann** [comment] 2024-09-30 14:58
I haven't managed to reproduce this issue on macOS.

**Comment by SilkeSchomann** [comment] 2024-10-01 07:40
I am closing this as I cannot reproduce this on macOS despite several attempts.

**Closed by SilkeSchomann** 2024-10-01 07:40 UTC
Labels: bug
